# Generated by Django 5.1.4 on 2026-07-16 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('author_name', models.CharField(max_length=100, verbose_name='Name')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Forum topic',
                'verbose_name_plural': 'Forum topics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('authors', models.CharField(max_length=500, verbose_name='Authors')),
                ('journal', models.CharField(max_length=250, verbose_name='Journal')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Volume')),
                ('article_number', models.CharField(blank=True, max_length=100, verbose_name='Article number or pages')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('doi', models.URLField(blank=True, verbose_name='DOI URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('published', models.BooleanField(default=True, verbose_name='Visible on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scientific publication',
                'verbose_name_plural': 'Scientific publications',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Name')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Reply')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='home.forumreply')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='home.forumtopic')),
            ],
            options={
                'verbose_name': 'Forum reply',
                'verbose_name_plural': 'Forum replies',
                'ordering': ['created_at'],
            },
        ),
    ]
